# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f909a882cebef8b990cb1dd7f4d497ba76e09d155339c4664f6e087fc24c24161c89e9544832fa570567e21d4136ab00adaa4059f361b6ba51e04464fbe9d688

test:
  secret_key_base: c8dd88e5506c80a5d6033b5a049ba60a1caaf66ea4646beba904721b6c2d07eca474ffff1391f9ac72811c2cc36d0da9b17d9cfef2a6bde07ffc88db164f8fab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
